### ISSUE TITLE
What unpaired data is used during IBT training?

### ISSUE THREAD

**Issue by Aolius** [laihuiyuan/Generic-resources-for-TST#1]
Hi, thanks for sharing your work and code.

May I ask a question about the data you used? Did you use any GYAFC training data during the IBT training and the final training (generating high-quality pairs)? Or did you only use the generic resource data for these training?

**Comment by laihuiyuan** [comment]
Thanks for your interest in our work.
For the formality transfer task, we used GYAFC training data, but the sentence pairs are not used for training, that is, we shuffled the pairs randomly.

**Comment by Aolius** [comment]
> Thanks for your interest in our work. For the formality transfer task, we used GYAFC training data, but the sentence pairs are not used for training, that is, we shuffled the pairs randomly.

Thanks for your reply! If I understand it correctly, during the final training stage, the generated high-quality pairs are generated by matching unpaired informal sentences X to Y' and formal sentences Y to X', so that we have pseudo-parallel data (X, Y') and (X', Y) to train the models in a supervised way. Is that correct?

**Comment by laihuiyuan** [comment]
> > Thanks for your interest in our work. For the formality transfer task, we used GYAFC training data, but the sentence pairs are not used for training, that is, we shuffled the pairs randomly.
> 
> Thanks for your reply! If I understand it correctly, during the final training stage, the generated high-quality pairs are generated by matching unpaired informal sentences X to Y' and formal sentences Y to X', so that we have pseudo-parallel data (X, Y') and (X', Y) to train the models in a supervised way. Is that correct?

Exactly! And we only used pseudo-parallel data from one direction to train the model of the opposite direction. For example, the pseudo-parallel (X, Y') that is generated by the model transforming informal sentences into formal ones, which is used to train the model transforming formal sentences into informal ones. This is because we want the sentence on the target side  (it is X here, for example) to be "natural".
