### ISSUE TITLE
Parabank 2 data

### ISSUE THREAD

**Issue by VanHoang85** [laihuiyuan/Generic-resources-for-TST#2]
Hi,

Thanks for the work. I want to do some similar work with emotion style transfer for my thesis. However, I can"t download the ParaBank 2 dataset for the first pre-training. Can you upload it?

Best,
Van

**Comment by laihuiyuan** [comment]
Hi Van! Thanks for your interest in our work. I had also noted this issue, but I am afraid that I can not distribute the dataset since I am not the author of this. I think you could send an email to the author asking about the dataset.

**Comment by VanHoang85** [comment]
Yes, I just got a reply from the author. The new link is http://cs.jhu.edu/~vandurme/data/parabank-2.0.zip
