### ISSUE TITLE
negative to positive transition doesn't turn out well

### ISSUE THREAD

**Issue by li-jing-wen** [laihuiyuan/Generic-resources-for-TST#6]
Hi! I have followed your instructions to the last step: Finaly training with high-quality pairs and then generation.
For the YELP dataset, positive to negative conversion can yield good results, but the negative to positive training is not ideal, with a bleurt score of -0.035 and a style score of only 0.620. (It was observed that in my Step 3 Further Pre-training, the effect from negative to positive was also not ideal)
Do you have a different setup for transitioning from negative to positive during supervised training?

**Comment by laihuiyuan** [comment]
Hi! To maximise the quality of synthetic pairs, we choose sentences that contain one polarity word only, and swap that one with its antonym. But I saw in the log (in the last issue) that you used all synthetic pairs. Maybe you can check with this.

**Comment by li-jing-wen** [comment]
> Hi! To maximise the quality of synthetic pairs, we choose sentences that contain one polarity word only, and swap that one with its antonym. But I saw in the log (in the last issue) that you used all synthetic pairs. Maybe you can check with this.

In the final stage of high-quality parallel data screening, I use the style classifier and bleurt index together to select the sentences. In this way, the style of the sentence pair and the text quality will be high. Is it because the existence of multiple style words in the sentence will affect the quality of the training during the transfer from negative to positive direction? 
In addition, I am curious that using the same data for training, positive to negative conversion effect is very good. Is this the case for you?

**Comment by laihuiyuan** [comment]
As a final step, we select high-quality pairs using BLEURT and the style classifier. Then, the outputs of one direction and their corresponding source sentences are used to train the model of the opposite direction, so the training data is different for the two directions.
