### ISSUE TITLE
A question in step2 and step3

### ISSUE THREAD

**Issue by FayeXXX** [laihuiyuan/Generic-resources-for-TST#7]
Thank you for your excellent job. I have a question about the code, and I'm wondering if u could help me figure them out?

In step2(Generating Sentence-pairs from Generic Resources), I think "Generate sentence-pairs using WordNet" should be the last process instead of the 2nd. And how many files will be generated by pair_wordnet.py? Are they negative and positive for the source and the target respectively, thus four files to output? If the above thoughts are right, how should I put these files in step3?

It would be appreciated if you could reply. Thank you again for your patience.

**Comment by laihuiyuan** [comment]
Hi!

In the second step we create synthetic pairs with WordNet for further pre-training.

Regarding pair_wordnet.py, you can see the details of the arguments here: https://github.com/laihuiyuan/generic-resources-for-tst/blob/main/utils/pair_wordnet.py#L88-L93. You will get two output files containing original sentences and changed sentences, respectively

You can change the placement path of the data used for training: https://github.com/laihuiyuan/generic-resources-for-tst/blob/main/utils/dataset.py#L53-L54.
